### ISSUE TITLE
Cursor jumping

### ISSUE THREAD

**Issue by IngwiePhoenix** [IndigoUnited/js-md-highlight#4]
The cursor jumps around a very lot while typing, making it almost impossible to type out whole paragraphs without messing up the entire document.

Reproduce:
- `git clone` the repo.
- `bower install`
- `npm i -g http-server`
- `http-server`

Visit `http://localhost:8080` and head to the playground. Type in it, and the behaviour should come up.

Using Chrome 46.

**Comment by satazor** [comment]
Hi @IngwiePhoenix 

This module is not finished and it has a lot of stuff to be done. I suggest you find an alternative module or you can continue my work if you want.

Sorry.

**Comment by IngwiePhoenix** [comment]
I just coupled this and [this](https://github.com/SjonHortensius/LRTEditor) and got no cursor jumping at all. Then again, it uses a plugin to get around a few quirks. I also had to turn off line numbering to have it work properly. Now, that works.

So it might just be Chrome's default behavior with `contenteditable` or something.
